const Home = () => (
  <>
    <div className="flex flex-col space-y-4 mx-auto max-w-3xl px-4 sm:px-6 xl:max-w-5xl xl:px-0 my-10">
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Dui nunc mattis enim ut tellus elementum. Odio eu feugiat pretium nibh ipsum consequat nisl vel pretium. Ultrices gravida dictum fusce ut placerat orci nulla pellentesque dignissim. A condimentum vitae sapien pellentesque habitant morbi. Nunc sed blandit libero volutpat sed cras ornare. Elit duis tristique sollicitudin nibh sit. In nibh mauris cursus mattis molestie a iaculis at. Dis parturient montes nascetur ridiculus mus mauris vitae ultricies. Non pulvinar neque laoreet suspendisse. Lacus vestibulum sed arcu non odio.</p>
      <p>In ornare quam viverra orci sagittis eu volutpat. Viverra justo nec ultrices dui sapien eget mi proin. Ultrices dui sapien eget mi proin sed libero enim. Amet volutpat consequat mauris nunc. Egestas purus viverra accumsan in nisl. Aliquet sagittis id consectetur purus ut faucibus. Quisque non tellus orci ac auctor augue mauris augue neque. Id velit ut tortor pretium viverra suspendisse potenti nullam ac. At in tellus integer feugiat scelerisque varius. Nibh nisl condimentum id venenatis. Quis viverra nibh cras pulvinar. Fermentum dui faucibus in ornare. Lectus sit amet est placerat. Facilisis gravida neque convallis a cras semper auctor.</p>
      <p>Nisi est sit amet facilisis magna etiam. Aliquet nec ullamcorper sit amet risus. Suspendisse interdum consectetur libero id faucibus. Sed elementum tempus egestas sed sed risus pretium quam. Pharetra sit amet aliquam id diam maecenas ultricies mi. Risus viverra adipiscing at in tellus integer feugiat scelerisque varius. In hac habitasse platea dictumst quisque sagittis purus sit amet. Dictum varius duis at consectetur. Ut lectus arcu bibendum at varius. Id velit ut tortor pretium viverra suspendisse potenti nullam. Vel facilisis volutpat est velit egestas dui id. Felis eget velit aliquet sagittis id consectetur purus. Vestibulum mattis ullamcorper velit sed. Nisi est sit amet facilisis magna etiam tempor. Nam libero justo laoreet sit. Rhoncus aenean vel elit scelerisque mauris pellentesque. Commodo nulla facilisi nullam vehicula ipsum. Phasellus egestas tellus rutrum tellus pellentesque eu tincidunt tortor.</p>
    </div>
  </>
)

export default Home
